#!/bin/sh

mkdir -p opk
cp snes9x4d.dge opk/snes9x4d.dge
cp ../snes-pad_icon_32.png opk/icon.png

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=SNES9x4D
Comment=SuperFamicom emulator
Exec=snes9x4d.dge %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rg99.desktop

mksquashfs ./opk snes9x4d_rg99.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
